import {
  LayoutDashboard,
  Plane,
  CalendarCheck,
  Wallet,
  Users,
  FileText,
  Settings,
  Bell,
  Building2,
  Shield,
  BarChart3,
  UserCog,
  Home,
  CreditCard,
  Map,
  Globe,
  Briefcase,
  Tag,
  Package,
  Star,
  Heart,
  MessageSquare,
  HelpCircle,
  Lock,
  Key,
  Mail,
  Phone,
  Clock,
  Search,
  Filter,
  Download,
  Upload,
  Trash2,
  Edit,
  Eye,
  Plus,
  type LucideIcon,
} from "lucide-react"

const iconMap: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  "plane": Plane,
  "calendar-check": CalendarCheck,
  "wallet": Wallet,
  "users": Users,
  "file-text": FileText,
  "settings": Settings,
  "bell": Bell,
  "building-2": Building2,
  "shield": Shield,
  "bar-chart-3": BarChart3,
  "user-cog": UserCog,
  "home": Home,
  "credit-card": CreditCard,
  "map": Map,
  "globe": Globe,
  "briefcase": Briefcase,
  "tag": Tag,
  "package": Package,
  "star": Star,
  "heart": Heart,
  "message-square": MessageSquare,
  "help-circle": HelpCircle,
  "lock": Lock,
  "key": Key,
  "mail": Mail,
  "phone": Phone,
  "clock": Clock,
  "search": Search,
  "filter": Filter,
  "download": Download,
  "upload": Upload,
  "trash-2": Trash2,
  "edit": Edit,
  "eye": Eye,
  "plus": Plus,
}

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? LayoutDashboard
}
